<?php
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Shark
 * @package    Admin
 * @subpackage Views
 * @author     Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright  2012 Shark Web Intelligence
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version    ${CURRENT_VERSION}
 * @link       http://www.sharkwebintelligence.com
 */
?>
<?
  if ($this->canCreate):
  $params = isset($this->actionParams['create']) ? $this->actionParams['create'] : array();
?>
<div class="btn-toolbar pull-right">
  <div class="btn-group">
    <a class="btn btn-success btn-large" href="<?= $this->url(array_merge(array('module' => $this->module, 'controller' => $this->controller, 'action' => 'create'), $params), $this->createRoute, true) ?>">
      <?= isset($this->createEntityText) ? $this->createEntityText : $this->translate('SHARK_SCAFFOLD_NEW_ENTITY', $this->entityTitle) ?>
    </a>
  </div>
</div>
<?php endif; ?>