<div class="span12">
	<?= $this->partial('scaffold/messages.phtml', $this) ?>
	<a href="<?= $this->url(array(), $this->indexRoute, true) ?>" class="btn btn-large">
		<?= $this->translate('SHARK_SCAFFOLD_BACK_TO_LIST') ?>
	</a>
	<h3>
		<?= (isset($this->updateEntityText) ? $this->updateEntityText : $this->translate('SAHRK_SCAFFOLD_EDIT_ENTITY', $this->entityTitle)) ?>
	</h3>
	<?= $this->form ?>
</div>