<?
/**
 * Title
 */
$this->headTitle('Baja Salads');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'La realidad del uso del internet por los consumidores del mercado local');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Local Marketing</h1>
			<h2>Promocion de tu negocio en el mercado local</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Local Marketing') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<img src="<?= $this->absoluteUrl('img/local-marketing/local-marketing.jpg') ?>" alt="Busquedas de los consumidores" itemprop="image" />
			</div>
			<div class="span9">
				<h3>¿Cómo funciona?</h3>
				<p>Shark Local Marketing responde a un método de acción cíclico que incluye implementar todas las herramientas de nuestro servicio paso por paso.</p>
			</div>
			<div class="span9">
				<h3>Página de internet</h3>
				<div class="span3">

					<img src="<?= $this->absoluteUrl('img/local-marketing/website-icon-128x128.png') ?>" alt="Busquedas de los consumidores" itemprop="image" />
				</div>
				<div class="span6 last">
					
					<p>Primero hay que generar presencia. Esto se resuelve teniendo tu propia página de internet. Aquí resuelves las primeras preguntas fundamentales: quién eres, qué vendes, dónde te localizan y cómo te contactan.</p>
				</div>
			</div>
			<div class="span9">
				<h3>Redes Sociales</h3>
				<div class="span3">
					<img src="<?= $this->absoluteUrl('img/local-marketing/social-icon-128x128.png') ?>" alt="Busquedas de los consumidores" itemprop="image" />
				</div>
				<div class="span6 last">
					<p>Paralelamente a través de las redes sociales hacemos que tu empresa conecte con simpatizantes o seguidores a quienes mostrar tus productos y servicios. De la misma manera generas conversaciones, ganas seguidores, creas fidelidad y envías tráfico a tu página de Internet. La estrategia debe estar enfocada a dos segmentos.</p>
					<ul>
						<li><strong>A tus seguidores:</strong> llegamos con publicaciones de tu página, tweets, pins y otros contenidos originales.</li>
						<li><strong>A los que no te siguen:</strong> los alcanzamos con anuncios patrocinados en redes sociales para que formen parte de tus seguidores.</li>
					</ul>
				</div>
			</div>
			<div class="span9">
				<h3>Motores de búsquedas</h3>
				<div class="span3">
					<img src="<?= $this->absoluteUrl('img/local-marketing/search-icon-128x128.png') ?>" alt="Busquedas de los consumidores" itemprop="image" />
				</div>
				<div class="span6 last">
					
					<p>Continuamos el ciclo promocional con los motores de búsqueda. Con ellos hacemos que tu página tenga presencia en internet. En tu sitio creamos “landing pages” para cada uno de los productos para que cuando los busquen, los resultados de los mótores de búsqueda los lleven de manera directa a ese landing page y ofrezcas directamente tu producto o servicio. Para ello hay dos maneras de hacerlo.</p>
					<ul>
						<li><strong>Organica:</strong> Es decir, que de de manera natural mediante el uso de SEO, tu sitio se coloque dentro de los resultados de búsquedas</li>
						<li><strong>Pagada:</strong> A través de anuncios pagados en google llevamos a ese cliente potencial a la página especializada en el producto o servicio que ofreces y el visitante busca.</li>
					</ul>
				</div>
			</div>
			<div class="span9">
				<h3>Correo Electrónico<h3>
				<div class="span3">
					<img src="<?= $this->absoluteUrl('img/local-marketing/mail-icon-128x128.png') ?>" alt="Busquedas de los consumidores" itemprop="image" />
				</div>
				<div class="span6">
					
					<p>A través de tu sitio web, tus redes sociales e incluso en tu propio negocio, captamos las direcciones de correo electrónico de tus clientes y mediante un sistema de envío de correo masivo llamado newsletter, les enviamos invitaciones boletines y flyers electrónicos  con tus ofertas productos y servicios.</p>
				</div>
			</div>
			<div class="span9">
				<h3>Web Analytics</h3>
				<div class="span3">
					<img src="<?= $this->absoluteUrl('img/local-marketing/analytics-icon-128x128.png') ?>" alt="Busquedas de los consumidores" itemprop="image" />
				</div>
				<div class="span6">
					
					<p>Finalmente con esta herramienta, medimos el comportamiento y los resultados de tus esfuerzos de publicidad en internet, nos sirve para verificar la efectividad de nuestras campañas y nos ofrece los datos o la pauta para hacer los ajustes necesarios en caso de que nuestras campañas lo requieran para lograr una mayor precisión.</p>
				</div>
			</div>
		</div>
	</div>
	