<?
/**
 * Title
 */
$this->headTitle('Baja Salads');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Baja Salads');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Local Marketing</h1>
			<h2>Promocion de tu negocio en el mercado local</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Local Marketing') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<img src="<?= $this->absoluteUrl('img/local-marketing/datos-internet-guaymas.jpg') ?>" alt="Internet en Guaymas" itemprop="image" />
			</div>
			<div class="span9">
				<h3>¿Local qué?</h3>
					<p>En Guaymas hay poco más de 65,000 usuarios de internet. Nueve de cada diez de ellos tienen una cuenta en facebook, utilizan el correo electrónico y realizan sus búsquedas en Google. Muchos utilizan dispositivos móviles con acceso a la red o son usuarios de teléfonos inteligentes como Blackberry, iPhone o Galaxy, utilizan tabletas como iPad, Galaxy Tab o Playbook.</p>
					<p>Las demandas cotidianas exigen tener nuestros productos favoritos a la mano o al menos, al alcance de un clic. No estar en la red es un error equiparable a lo que en su momento era no aparecer en las páginas amarillas del directorio telefónico.</p>
				<h3>¿Apoco hay quienes me andan buscando y comparando?</h3>
					<p>Es cierto, todos buscamos ahorrar haciendo análisis de costo beneficio. Para ello hay que investigar distintos proveedores del servicio requerido, sus costos y quizás algún historial de clientes. ¿Qué te hace pensar que tus clientes no están buscándote justo ahora?</p>
				<h3>¿O sea que necesito una página web?</h3>
					<p>Todo comercio local comparte prácticamente el mismo mercado. Para obtener resultados diferentes, hay que tomar acciones distintas a las de tus competidores. El objetivo es sobresalir y potencializar a su favor, las fortalezas de sus servicios hacia sus clientes y potenciales nuevos clientes. Crear fidelidad, adquirir nuevos consumidores y crear una reputación positiva.</p>
					<p>Shark Local Marketing es el producto innovador que resuelve esas necesidades. Si no estás en la red, te pone en el terreno donde están sucediendo las cosas. Ofrece información precisa de sus servicios y productos. Abre canales de comunicación y promoción en redes sociales. Genera fidelidad y mantiene la reputación que su negocio requiere. Estamos convencidos que todo aquel negocio que desee tener una estrecha relación con sus clientes y prospectos debe contar con un sitio web en el cual pueda responder a las preguntas básicas de su mercado.</p>
					<p>¿Qué o quién es? ¿Qué vende? ¿Dónde está ubicado? ¿Cómo lo contacto?</p>
				<h3>¿Cómo le haré para que la gente sepa que tengo una página web?</h3>
					<p>Esto se complementa con aplicaciones sociales como Facebook, Twitter, Foursquare, Pinterest, YouTube, LinkedIn, redes sociales tan cotidiana por los usuarios que pueden pagar por sus servicios.</p>
					<p>Implementamos estrategias de promoción vía correo electrónico para sus actuales clientes y desarrollamos campañas promocionales con anuncios patrocinados en Facebook y Google para hacernos de un público nuevo, perfectamente segmentado hacia quienes reúnen el perfil de edad, sexo y ubicación de sus potenciales clientes.</p>
					<div class="center">
						<h3>
							<a href="<?= $this->url(array(), 'contact') ?>" class="btn btn-large btn-primary">
								¿Estás listo para ser parte de esta nueva corriente de negocios exitosos?
							</a>
						</h3>
					</div>
			</div>
		</div>
	</div>

