<?
/**
 * Title
 */
$this->headTitle('Baja Salads');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Baja Salads');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Local Marketing</h1>
			<h2>Promocion de tu negocio en el mercado local</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Local Marketing') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<img src="<?= $this->absoluteUrl('img/local-marketing/datos-internet-guaymas.jpg') ?>" alt="Internet en Guaymas" itemprop="image" />
			</div>
			<div class="span9">
				<h3>Introducción</h3>
					<p>Hoy en día, la gran mayoría de los hogares cuentan con una computadora conectada a internet, en Guaymas existen alrededor de 40,000 usuarios de internet, 9 de cada 10 de ellos tienen una cuenta de Facebook, todos ellos tienen una cuenta de correo electrónico y utilizan a Google para realizar búsquedas. De la misma manera el uso de dispositivos móviles con acceso a internet, o los también llamados smartphones como los son el Blackberry, el iPhone de Apple o el Galaxy de Samsung, así como los  tablets como el Playbook, iPad o el Galaxy Tab son cada día mas populares entre la gente de nuestra ciudad. Esta gente mediante el uso de estos dispositivos móviles accede a los servicios de búsqueda por internet para encontrar los productos y servicios que requieren.</p>
					<p>Para cualquier consumidor es importante saber con quién va a hacer un trato, normalmente antes de una operación de compra venta, este realiza una investigación previa de posibles vendedores y los precios de sus productos o servicios, la idea es obtener la mejor calidad al mejor precio.</p>
					<p>Todos los negocios tienen un nicho de mercado que comparten con sus competidores, el porcentaje de participación en ese segmento de mercado que tu negocio puede lograr, depende directamente de que tan conocido sea por tus posibles clientes; debemos tomar en cuenta que  existen bastantes personas que tienen necesidad de los productos o servicios que tu negocio ofrece, el problema es que en la mayoría de los casos, esos que tienen la necesidad, no saben que tu negocio existe, que es lo que vendes, donde estas ubicado y como te pueden contactar. Este problema de popularidad no es lo único con lo que tu negocio se va a enfrentar, también necesita crear y mantener una correcta reputación, por ultimo tu negocio necesita un medio eficaz de dar a conocer sus ofertas, productos y servicios a sus clientes y prospectos.</p>
					<p>En Shark Local Marketing nuestra bandera se llama Innovación; estamos convencidos que todo aquel negocio que desee tener una estrecha relación con sus clientes y prospectos debe contar con un sitio web en el cual pueda responder a las preguntas básicas de su mercado, es decir:</p>
					<ul>
					<li>¿Qué o quién es?</li>
					<li>¿Qué vende?</li>
					<li>¿Dónde está?</li>
					<li>¿Cómo lo contacto?</li>
					</ul>
					<p>
					Además debe contar con los canales de redes sociales más populares del momento como Facebook, Twitter, Foursquare, Pinterest, YouTube, LinkedIn, para que mediante estos se logre crear la popularidad y la reputación de tu negocio en línea.
					</p>
					<p>
					Para promover tu negocio utilizamos campañas de envío masivo de correo electrónico para tus clientes actuales y anuncios pagados en Facebook y Google para alcanzar  aquellos que aun andan buscando los productos y servicios de tu negocio ofrece.
					</p>
				</div>
			</div>
		</div>
	</div>