<div class="span12">
	<div id="main-carousel" class="jumbo">
		<?= $this->carousel($this->slides) ?>
	</div>
</div>
<div itemscope itemtype="http://schema.org/Corporation" class="span12">
	<article id="description">
		<h1 itemprop="name">Shark Web Intelligence</h1>
		<div itemprop="description">
			<p>Somos una empresa dedicada el diseño y desarrollo web orientado a la generación de tráfico y comercio electrónico, análisis de tráfico, administración de campañas de web marketing, optimización en motores de búsqueda y hosting.</p>
		</div>
	</article>
</div>
<div id="services">
	<!--<div class="span12 heading">
		<h3>Nuestros servicios</h3>
	</div>-->
	<?= $this->services(null, 4) ?>
	<div class="span3 offset9">
		<p class="pull-right">
			<a href="<?= $this->url(array('page' => 'servicios',), 'pages') ?>" class="more-link" title="<?= $this->translate('services_full_list') ?>"><?= $this->translate('services_full_list') ?></a>
		</p>
	</div>
</div>
<!--<div id="clients">
	<div class="span12 heading">
		<h3>Algunos de nuestros clientes</h3>
	</div>
	<?= $this->clients(null, 4) ?>
	<div class="span3 offset9">
		<p class="pull-right">
			<a href="<?= $this->url(array('page' => 'los-clientes',), 'pages') ?>" class="more-link" title="<?= $this->translate('clients_full_list') ?>"><?= $this->translate('clients_full_list') ?></a>
		</p>
	</div>
</div>
<div id="projects">
	<div class="span12 heading">
		<h3>Tecnologias</h3>
	</div>
</div>-->