<?
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Site
 * @package    Default
 * @subpackage Views
 * @author     Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright  2012 Shark Web Intelligence
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version    ${CURRENT_VERSION}
 * @link       http://www.sharkwebintelligence.com
 */
$this->minifyHeadLink()->appendAlternate($this->absoluteUrl($this->url(array(), 'rss-blog')), 'application/xml-rss', $this->title . ' - Blog');
?>
<div class="span12">
	<div id="main-carousel" class="jumbo">
		<?= $this->carousel($this->slides) ?>
	</div>
</div>
<div itemscope itemtype="http://schema.org/Corporation" class="span12">
	<article id="description">
		<h1 itemprop="name">Shark Web Intelligence</h1>
		<div itemprop="description">
			<p>Somos una empresa dedicada el diseño y desarrollo web orientado a la generación de tráfico y comercio electrónico, análisis de tráfico, administración de campañas de web marketing, optimización en motores de búsqueda y hosting.</p>
		</div>
	</article>
</div>
<div id="services">
	<!--<div class="span12 heading">
		<h3>Nuestros servicios</h3>
	</div>-->
	<?= $this->services(null, 4) ?>
	<div class="span3 offset9">
		<p class="pull-right">
			<a href="<?= $this->url(array('page' => 'servicios',), 'pages') ?>" class="more-link" title="<?= $this->translate('services_full_list') ?>"><?= $this->translate('services_full_list') ?></a>
		</p>
	</div>
</div>
<!--<div id="clients">
	<div class="span12 heading">
		<h3>Algunos de nuestros clientes</h3>
	</div>
	<?= $this->clients(null, 4) ?>
	<div class="span3 offset9">
		<p class="pull-right">
			<a href="<?= $this->url(array('page' => 'los-clientes',), 'pages') ?>" class="more-link" title="<?= $this->translate('clients_full_list') ?>"><?= $this->translate('clients_full_list') ?></a>
		</p>
	</div>
</div>
<div id="projects">
	<div class="span12 heading">
		<h3>Tecnologias</h3>
	</div>
</div>-->