<?
/**
 * Title
 */
$this->headTitle('Análisis web');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Servicios de análisis y monitoreo web.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Análisis web</h1>
		<h2>Lorem ipsum dolor sit amet.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-analytics">
	<div class="span3">
		<p>El análisis web (web analytics) comprende la recolección, medición, análisis y reporte de datos relativos a un sitio web con el fin de entender el comportamiento de su tráfico y tener un punto de referencia para la optimización de sus recursos tales como su esquema de navegación o su contenido.</p>
		<p>Mediante este estudio podemos saber el origen y el comportamiento de los visitantes de nuestro sitio web, cuales son sus paginas mas populares, el tiempo promedio que permanece en el un visitante, cuantos de esos visitantes son nuevos y cuantos son recurrentes.</p>
	</div>
	<div class="span6 last">
		<img src="<?= $this->baseUrl('/img/430x200.png') ?>" class="full-width" alt="Análisis web" width="430" height="200">
	</div>
	<div class="span9 last">
		<p>En resumen, el análisis web es una potente herramienta que nos sirve para determinar el éxito de nuestro sitio web y a detectar sus áreas débiles, para que estas sean corregidas y pueda alcanzarse el nivel de satisfacción y popularidad esperado.</p>
	</div>
	<div class="hr">
	</div>
	<div class="span9 heading">
		<h3>¿Análisis qué?</h3>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/webalizer.jpg') ?>" alt="" class="full-width" width="270" height="165">
		<p>Webalizer.</p>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/google-analytics.jpg') ?>" alt="" class="full-width" width="270" height="165">
		<p>Google Analytics.</p>
	</div>
	<div class="span3 last">
		<ul class="checklist">
			<li>On-site web analytics</li>
			<li>Off-site web analytics.</li>
		</ul>
	</div>
	<div class="span9 heading">
		<h4>Análisis On-site</h4>
	</div>
	<div class="span9 last">
		<p>El análisis web en sitio (on-site web analytics) mide el comportamiento y la manera en que es utilizado un sitio web por sus visitantes.</p>
		<p>El principal propósito del analisis web en sitio (on-site web analytics) es medir el rendimiento de nuestro sitio web en un contexto comercial. Nos provee de información que nos permite saber por ejemplo, cuáles con las páginas de aterrizaje (landing pages) que hacen que nuestros visitantes compren en nuestro sitio.</p>
		<p>Mediante el análisis web en sitio, podemos saber:</p>
	</div>
	<div class="span5">
		<ul class="checklist">
			<li>¿Quiénes visitan mi sitio web?</li>
			<li>¿Qué es lo que están haciendo los visitantes de mi sitio web? o mejor aún</li>
			<li>¿Qué están tratando de hacer?</li>
			<li>¿Cuál es la diferencia entre lo que están haciendo y lo ideal?, y si nos referimos a: ¿lo ideal para mi negocio? o ¿lo ideal para el cliente?</li>
			<li>¿Cuáles son las maneras concretas de eliminar estas diferencias?</li>
			<li>¿Cómo podemos obtener más de estas personas?</li>
		</ul>
	</div>
	<div class="span4 last">
		<blockquote>
			<p>Praesent nec aliquet elit. Nullam convallis placerat metus, sit amet ultrices nulla faucibus sit amet. Quisque dictum lorem sedep sem lacinia adipiscing egestas quis.</p>
			<p><strong>John Doe</strong>, Some Business.</p>
		</blockquote>
	</div>
	<div class="span9 heading">
		<h4>Análisis Off-site</h4>
	</div>
	<div class="span5 last">
		<p>El análisis web fuera de sitio (Off-site web analytics) puede ser realizado independientemente de poseer o no un sitio web. Se refiere a la medición y análisis de tres factores importantes en in sitio web: La audiencia potencial, su visibilidad y los comentarios.</p>
		<h5>Potential audience (oportunidad)</h5>
		<p>La audiencia potencial de un sitio web se refiere al mayor número de posibles visitantes interesados en los contenidos, productos o servicios que ofrece un sitio web.
Analizar la audiencia potencial nos permite llegar a través de nuestro sitio web a todos aquellos usuarios de internet <strong>****CHEK****</strong> en que y esta se define en función de los productos o servicios que se ofrecen y de los objetivos fijados para nuestro sitio web.</p>
		<h5>Share of Voice (índice de participación)</h5>
		<p>Indicador que expresa en términos porcentuales la exposición y visibilidad de una campaña publicitaria online en comparación con sus competidoras o con la totalidad de su sector. Un aumento de la presencia repercute sobre la cuota de mercado, aunque es un error frecuente considerar que el SOV corresponde a una determinada inversión publicitaria, puesto que la segunda no tiene por qué traducirse necesariamente en la primera.</p>
		<h5>Buzz (comentarios)</h5>
		<p>Se refiere al creciente interés que puede surgir de manera natural entre los usuarios y que se manifiesta en un aumento de la información, del número de conversaciones o de búsquedas acerca de un producto o servicio.</p>
		<p>El término representa el estado de opinión de un mercado respecto a una marca, por lo que no posee una connotación determinada, aunque en su vertiente positiva, es el principal objetivo de todas aquellas prácticas de marketing desarrolladas en la Web 2.0.</p>
	</div>
	<div class="span4 last">
		<blockquote>
			<p>Praesent nec aliquet elit. Nullam convallis placerat metus, sit amet ultrices nulla faucibus sit amet. Quisque dictum lorem sedep sem lacinia adipiscing egestas quis.</p>
			<p><strong>John Doe</strong>, Some Business.</p>
		</blockquote>
	</div>
</div>