<?
/**
 * Title
 */
$this->headTitle('Desarrollo web');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Servicios de desarrollo de aplicaciones web.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Desarrollo web</h1>
		<h2>Utilizamos tecnologías de vanguardia y producimos código libre de errores.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-development">
	<div class="span3">
		<p>La integración precisa de las más sofisticadas tecnologías hacen del desarrollo web una parte fundamental dentro de la creación de un sitio electrónico. Esa es la razón principal por la que nos actualizamos constantemente para ofrecer a nuestros clientes, soluciones integrales.
		</p>
	</div>
	<div class="span6 last">
		<img src="<?= $this->baseUrl('/img/services/web-development-570x217.jpg') ?>" class="full-width" alt="Desarrollo web" width="570" height="217">
	</div>
	<div class="span9 last">
		<p>
		Los productos que desarrollamos en la actualidad cumplen con los más altos estándares dentro de la programación web, utilizando tecnologías como HTML 5 y CSS 3 cumpliendo con los estándares internacionales W3C.</p>
	</div>
	<div class="hr">
	</div>
	<div class="span9 heading">
		<h3>¿Porque elegir a Shark Web Intelligence?</h3>
	</div>
	<div class="span9 last">
		<p>Por que todo proyecto es ejecutado a la medida de las necesidades de nuestros clientes. Incluye programación original y estandarizada internacionalmente como un símbolo de calidad y eficacia. Trabajamos con pasión creyendo que nuestra entrega se verá reflejado en el éxito de nuestros proyectos.</p>
	</div>
	
</div>