<?
/**
 * Title
 */
$this->headTitle('Diseño web');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Servicios de diseño web.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Dise&ntilde;o web</h1>
		<h2>Actual, Funcional, Accesible, Dinamico y Responsivo.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-design">
	<div class="span3">
		<p>La funcionalidad de un sitio en su parte programática es tan importante como el factor visual y su usabilidad. Por ello ofrecemos soluciones de identidad gráfica y diseño web. Hagamos de su proyecto una realidad, funcional, eficaz y atractiva para el usuario.</p>
	</div>
	<div class="span6 last">
		<img src="<?= $this->baseUrl('/img/services/web-design-570x217.jpg') ?>" class="full-width" alt="Diseño web" width="570" height="217">
	</div>
	
</div>