<?
/**
 * Title
 */
$this->headTitle('Email marketing');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Manejo de campañas por correo.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Email marketing</h1>
		<h2>Promocionamos tu marca productos y sevicios mediante el correo electrónico.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-email-marketing">
	<div class="span3">
		<p>El mercado actual y sus necesidades evolucionan de forma paralela al desarrollo de herramientas tecnológicas. Eso nos obliga a estar constantemente actualizados para ofrecer el desarrollo e implementación de estrategias de marketing electrónico y comunicación interna y externa a través de herramientas digitales como son las redes sociales.</p>
	</div>
	<div class="span6 last">
		<img src="<?= $this->baseUrl('/img/services/email-marketing-570x217.jpg') ?>" class="full-width" alt="Email marketing" width="570" height="217">
	</div>
</div>
