<?
/**
 * Title
 */
$this->headTitle('Email marketing');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Manejo de campañas por correo.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Email marketing</h1>
		<h2>Promocionamos tu marca productos y sevicios mediante el correo electrónico.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-email-marketing">
	<div class="span3">
		<p>El mercado actual y sus necesidades evolucionan de forma paralela al desarrollo de herramientas tecnológicas. Eso nos obliga a estar constantemente actualizados para ofrecer el desarrollo e implementación de estrategias de marketing electrónico y comunicación interna y externa a través de herramientas digitales como son las redes sociales.</p>
	</div>
	<div class="span6 last">
		<img src="<?= $this->baseUrl('/img/services/email-marketing-570x217.jpg') ?>" class="full-width" alt="Email marketing" width="570" height="217">
	</div>
	<div class="hr">
	</div>
	<div class="span9 heading">
		<h3>Why pick us?</h3>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/205x125.png') ?>" alt="" class="full-width" width="205" height="125">
		<p>Nam eu sapien vel elit tempus.</p>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/205x125.png') ?>" alt="" class="full-width" width="205" height="125">
		<p>Bibendum eget elementum tortor.</p>
	</div>
	<div class="span3 last">
		<ul class="checklist">
			<li>Lorem ipsum dolor sit amet.</li>
			<li>Phasellus adipi commodo.</li>
			<li>Fusce iaculis lectus.</li>
			<li>Duis neque eros lacinia</li>
			<li>Aenean lobortis ipsum</li>
		</ul>
	</div>
	<div class="hr">
	</div>
	<div class="span9 last">
		<p>Aenean sed mauris id diam fermentum pretium. Cras consectetur diam nec nulla iaculis mattis. Phasellus iaculis sollicitudin sagittis. Proin semper feugiat ornare. Vivamus viverra suscipit bibendum. Fusce eu sem mauris, non pharetra ligula. Praesent facilisis eros quis dolor ullamcorper varius. Duis neque eros, lacinia adipiscing egestas quis, consequat a ipsum. Aenean lobortis ipsum id enim egestas iaculis. Vivamus eleifend dictum sagittis. Nam interdum tincidunt placerat. Nunc nisl leo, laoreet quis semper id, vestibulum vel ipsum.</p>
	</div>
	<div class="span5">
		<p>Vivamus luctus, dui interdum consequat vulputate, augue ligula vestibulum urna, non varius metus eros quis ante. Mauris nec auctor quam. Nullam laoreet erat sit amet nisi sollicitudin et vulputate ipsum elementum. Praesent vestibulum euismod mi vel suscipit.</p>
	</div>
	<div class="span4 last">
		<blockquote>
			<p>Praesent nec aliquet elit. Nullam convallis placerat metus, sit amet ultrices nulla faucibus sit amet. Quisque dictum lorem sedep sem lacinia adipiscing egestas quis.</p>
			<p><strong>John Doe</strong>, Some Business.</p>
		</blockquote>
	</div>
</div>