<?
/**
 * Title
 */
$this->headTitle('Servicios - Publicidad en Google');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Nuestros servicios - Publicidad en Google');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Servicios</h1>
		<h2>Publicidad en Google</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-hosting">
	<div class="span6">
		<img src="<?= $this->baseUrl('/img/pages/servicios.jpg') ?>" alt="Hospedaje web">
	</div>
	<div class="span3 last">
		<h2>Google AdWords</h2>
		<p>En Shark Web Intelligence, nuestra filosofía esta centrada en la palabra inovación y hemos desarrollado una estrategia para hacer que nuestros clientes tengan la mejor herramienta de promocion de su negocio.</p>
	</div>