<?
/**
 * Title
 */
$this->headTitle('e-Marketing');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Marketing electrónico.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Servicios</h1>
		<h2>Redes Sociales</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-hosting">
	<div class="span6">
		<img src="<?= $this->baseUrl('/img/pages/redes-sociales.jpg') ?>" class="full-width" alt="Redes sociales" width="570" height="217">
	</div>
	<div class="span3  last">
		<h2>Redes Sociales</h2>
		<p>El mercado actual y sus necesidades evolucionan de forma paralela al desarrollo de herramientas tecnológicas. 
		Eso nos obliga a estar constantemente actualizados para ofrecer el desarrollo e implementación de estrategias de marketing electrónico y comunicación interna y externa a través de herramientas digitales como son las redes sociales.</p>
	</div>

	<div class="hr">
	</div>
	<div class="span9 heading">
		<h3>Porque elegir a Shark Web Intelligence?</h3>
	</div>
	<div class="span9 last">
		<p>Todos sabemos que es importante estar ahí aunque muchos aún no saben para qué. Nosotros te ayudamos a entrar con una estrategia. Generamos soporte en la implementación de departamentos en marketing electrónico y redes sociales para empresas y lideramos campañas publicitarias online. La creatividad y la imaginación es el límite.</p>
	</div>
</div>