<?
/**
 * Title
 */
$this->headTitle('Hospedaje web');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Servicios de hospedaje web y cloud computing.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Sitios web</h1>
		<h2>Desarrollo web profesional.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-hosting">
	<div class="span6">
		<img src="<?= $this->baseUrl('/img/services/web-hosting-430x200.jpg') ?>" alt="Hospedaje web" width="430" height="200">
	</div>
	<div class="span3 last">
		<h2>Lorem ipsum dolor sit amet</h2>
		<p>Lorem ipsum dolor consequat incididunt aute eiusmod elit veniam dolore cillum consectetur culpa sint sit in dolor ad ut sit sint irure. </p>
	</div>
	<div class="hr">
	</div>
	<div class="span9 heading" id="hosting-features">
		<h3>Características</h3>
		<div class="span3">
			<h4>Panel de Control</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/tools.gif') ?>" width="32" heigth="32">Todas nuestras cuentas de hosting cuentan con el prestigiado cPanel.
			</p>
		</div>
		<div class="span3">
			<h4>Dominio</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/globe.gif') ?>" width="32" heigth="32">Nuestros planes de hosting incluyen 1 año de dominio gratis.
			</p>
		</div>
		<div class="span3 last">
			<h4>Bases de datos</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/database.gif') ?>" width="32" heigth="32">
				Nuestros planes cuentan con MySQL como motor de bases de datos.
			</p>
		</div>
		<div class="span3">
			<h4>Correo Electrónico</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/mail.gif') ?>" width="32" heigth="32">
				Todos nuestros planes incluyen el servico de correo electrónico personalizado.
			</p>
		</div>
		<div class="span3">
			<h4>Estadisticas de Trafico</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/pie.gif') ?>" width="32" heigth="32">
				Nuestros planes incluyen webalizar como herramienta para el monitoreo de tráfico en su sitio web.
			</p>
		</div>
		<div class="span3 last">
			<h4>Soporte Tecnico 24*7</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/question.gif') ?>" width="32" heigth="32">Contamos con un centro de soporte personalizado para su mayor satisfacción.
			</p>
		</div>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/205x125.png') ?>" alt="" class="full-width" width="205" height="125">
		<p>Nam eu sapien vel elit tempus.</p>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/205x125.png') ?>" alt="" class="full-width" width="205" height="125">
		<p>Bibendum eget elementum tortor.</p>
	</div>
	<div class="span3 last">
		<ul class="checklist">
			<li>Lorem ipsum dolor sit amet.</li>
			<li>Phasellus adipi commodo.</li>
			<li>Fusce iaculis lectus.</li>
			<li>Duis neque eros lacinia</li>
			<li>Aenean lobortis ipsum</li>
		</ul>
	</div>
	<div class="hr">
	</div>
	<div class="span9 last">
		<p>En shark web intelligence oferecemos a nuestros clientes el servicio de hospedaje web, el cual está diseñado para que los proyectos que desarrollamos residan en un escenario ideal para que su funcionamiento y rendimiento sean óptimos.
		</p>
		<p>
			Nuestro servicio de hospedaje web garantiza un excelente tiempo de respuesta, alta disponibilidad, alto rendimiento, gran estabilidad y soporte personalizado
		</p>
	</div>
	<div class="span5">
		<p>Vivamus luctus, dui interdum consequat vulputate, augue ligula vestibulum urna, non varius metus eros quis ante. Mauris nec auctor quam. Nullam laoreet erat sit amet nisi sollicitudin et vulputate ipsum elementum. Praesent vestibulum euismod mi vel suscipit.</p>
	</div>
	<div class="span4 last">
		<blockquote>
			<p>Praesent nec aliquet elit. Nullam convallis placerat metus, sit amet ultrices nulla faucibus sit amet. Quisque dictum lorem sedep sem lacinia adipiscing egestas quis.</p>
			<p><strong>John Doe</strong>, Some Business.</p>
		</blockquote>
	</div>
</div>