<?
/**
 * Title
 */
$this->headTitle('Hospedaje web');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Servicios de hospedaje web y cloud computing.');
?>
<div class="span12">

	<div class="jumbo">
		<div><h1>Servicios</h1>
		<h2>Nuestra solución para tus necesidades de publicidad.</h2></div>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>

<div class="span9 content right" id="services-web-hosting">
	<div class="span6">
		<img src="<?= $this->baseUrl('/img/pages/websites.jpg') ?>" alt="Hospedaje web">
	</div>
	<div class="span3 last">
		<h2>Website</h2>
		<p>El principal elemento de nuestra solucion es tu website, en este puedes mostrar todo lo refernte a tu empresa es decir: ¿quién eres?, ¿qué haces? ó ¿qué vendes?, ¿dónde estás? y ¿como te pueden contactar?</p>
		<!--<ul class="checklist fin">
			<li>¿quién eres?</li>
			<li>¿qué haces? ó ¿qué vendes?</li>
			<li>¿dónde estás?</li>
			<li>¿como te pueden contactar?</li>
		</ul> -->
	</div>
	<div class="span9">
		<p>En tu website no existen limites, creamos una seccion para colocar tus ofertas y promociones para que muestres a detalle todo aquello que quieres vender de una manera clara y eficiente y asi generar mas ventas.</p>
		<p>Lo mejor es que para cada una de tus promociones, crearemos un landing page, que es una pagina especializada en un producto en especifico en la cual mostramos todas las caracteristicas y argumentos de venta del producto que queremos vender, una forma de contacto y un sistema de comentarios para que tus clientes expresen su nivel de satisfaccion y opinion respscto de tu producto o servicio.</p>
	</div>
		<div class="span3">
			<h4>Panel de Control</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/tools.gif') ?>" width="32" heigth="32">Todas nuestras cuentas de hosting cuentan con el prestigiado cPanel.
			</p>
		</div>
		<div class="span3">
			<h4>Dominio</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/globe.gif') ?>" width="32" heigth="32">Nuestros planes de hosting incluyen 1 año de dominio gratis.
			</p>
		</div>
		<div class="span3 last">
			<h4>Bases de datos</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/database.gif') ?>" width="32" heigth="32">
				Nuestros planes cuentan con MySQL como motor de bases de datos.
			</p>
		</div>
		<div class="span3">
			<h4>Correo Electrónico</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/mail.gif') ?>" width="32" heigth="32">
				Todos nuestros planes incluyen el servico de correo electrónico personalizado.
			</p>
		</div>
		<div class="span3">
			<h4>Estadisticas de Trafico</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/pie.gif') ?>" width="32" heigth="32">
				Nuestros planes incluyen webalizar como herramienta para el monitoreo de tráfico en su sitio web.
			</p>
		</div>
		<div class="span3 last">
			<h4>Soporte Tecnico 24*7</h4>
			<p>
				<img src="<?= $this->baseUrl('img/services/icons/question.gif') ?>" width="32" heigth="32">Contamos con un centro de soporte personalizado para su mayor satisfacción.
			</p>
		</div>
	<div class="hr">
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/205x125.png') ?>" alt="" class="full-width" width="205" height="125">
		<p>Nam eu sapien vel elit tempus.</p>
	</div>
	<div class="span3">
		<img src="<?= $this->baseUrl('/img/205x125.png') ?>" alt="" class="full-width" width="205" height="125">
		<p>Bibendum eget elementum tortor.</p>
	</div>
	<div class="span3 last">
		<ul class="checklist">
			<li>Lorem ipsum dolor sit amet.</li>
			<li>Phasellus adipi commodo.</li>
			<li>Fusce iaculis lectus.</li>
			<li>Duis neque eros lacinia</li>
			<li>Aenean lobortis ipsum</li>
		</ul>
	</div>
	<div class="hr">
	</div>
	<div class="span9 last">
		<p>En shark web intelligence oferecemos a nuestros clientes el servicio de hospedaje web, el cual está diseñado para que los proyectos que desarrollamos residan en un escenario ideal para que su funcionamiento y rendimiento sean óptimos.
		</p>
		<p>
			Nuestro servicio de hospedaje web garantiza un excelente tiempo de respuesta, alta disponibilidad, alto rendimiento, gran estabilidad y soporte personalizado
		</p>
	</div>
	<div class="span5">
		<p>Vivamus luctus, dui interdum consequat vulputate, augue ligula vestibulum urna, non varius metus eros quis ante. Mauris nec auctor quam. Nullam laoreet erat sit amet nisi sollicitudin et vulputate ipsum elementum. Praesent vestibulum euismod mi vel suscipit.</p>
	</div>
	<div class="span4 last">
		<blockquote>
			<p>Praesent nec aliquet elit. Nullam convallis placerat metus, sit amet ultrices nulla faucibus sit amet. Quisque dictum lorem sedep sem lacinia adipiscing egestas quis.</p>
			<p><strong>John Doe</strong>, Some Business.</p>
		</blockquote>
	</div>
</div>