<?php
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Site
 * @package    Search
 * @subpackage Views
 * @author     Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright  2012 Shark Web Intelligence
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version    ${CURRENT_VERSION}
 * @link       http://www.sharkwebintelligence.com
 */
if ($this->query) {
	$this->headTitle('Buscando: ' . $this->query);
} else {
	$this->headTitle('Búsqueda');
}
?>
<form method="get" name="search">
	<label for="q">Búsqueda:</label>
	<input type="text" name="q" id="q" value="<?= $this->query ?>">
	<button type="submit" class="btn btn-primary">Buscar</button>
</form>
<? if ($this->hits) : ?>
<ul>
<? foreach ($this->hits as $hit) : ?>
	<li>
		<?= $hit->title ?>
	</li>
<? endforeach ?>
</ul>
<? endif ?>