<?
/**
 * Title
 */
$this->headTitle('Contacto');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Póngase en contacto con nosotros');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Contacto</h1>
		<h2>Contáctenos para un presupuesto sin compromiso</h2>
	</div>
</div>
<div class="span9 content right" id="services-overview">
	<p>Lorem ipsum dolor sit amet.</p>
</div>