<?
/**
 * Title
 */
$this->headTitle('El equipo');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Conoce a nuestro equipo de desarrollo y diseño.');
?>
<div class="span12">
	<div class="jumbo">
		<h3>El equipo</h3>
		<p>Conoce a nuestro equipo de trabajo</p>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Acerca') ?>
</div>
<div class="span9 content right" id="team">
	<div itemscope itemtype="http://schema.org/Person">
		<div class="span3 team-social">
			<div class="profile">
				<img src="<?= $this->absoluteUrl('/img/team/dherrerav.jpg') ?>" alt="David Herrerav" width="205" height="154" itemprop="image">
			</div>
			<ul>
				<li>
					<img src="<?= $this->baseUrl('/img/twitter.png') ?>" alt="David Herrera on Twitter" width="16" height="16">
					<a target="_blank" href="http://twitter.com/becomeashark" title="David Herrera on Twitter">@becomeashark</a>
				</li>
				<li>
					<img src="<?= $this->baseUrl('/img/facebook.png') ?>" alt="David Herrera on Facebook" width="16" height="16">
					<a target="_blank" href="http://facebook.com/sharkwebintelligence" title="David Herrera on Facebook">David Herrera</a>
				</li>
			</ul>
		</div>
		<div class="span6 last">
			<h3 itemprop="name"><a href="https://plus.google.com/103223395393674962309?rel=author" title="Google Plus profile">David Herrera</a></h3>
			<div itemprop="description">
				<p>TI specialist con 17 años de experiencia en el ramo. Apasionado de los motores de búsquedas y activista de la puntualidad extrema. Líder del equipo  e invitador involuntario de los cafés en la oficina.</p>
			</div>
		</div>
	</div>
	<div class="hr">
		&nbsp;
	</div>
	<div itemscope itemtype="http://schema.org/Person">
		<div class="span3 team-social">
			<img src="<?= $this->absoluteUrl('/img/team/samacs.png') ?>" alt="Saul Martínez" width="205" height="154" itemprop="image">
			<h3 itemprop="name"><a href="https://plus.google.com/109001202683700563599?rel=author" title="Google Plus profile">Saul Martínez</a></h3>
			<ul>
				<li>
					<img src="<?= $this->baseUrl('/img/twitter.png') ?>" alt="Saul Martínez on Twitter" width="16" height="16">
					<a target="_blank" href="http://twitter.com/samacs" title="Saul Martínez on Twitter">@samacs</a>
				</li>
				<li>
					<img src="<?= $this->baseUrl('/img/facebook.png') ?>" alt="Saul Martínez on Facebook" width="16" height="16">
					<a target="_blank" href="http://facebook.com/samacs" title="Saul Martínez on Facebook">Saul Martínez</a>
				</li>
			</ul>
			
			<div itemprop="description">
				<p> Programador y desarrollador web. Devorador de libros libre de distinciones de temáticas e idiomas. Músico ocasional y generador de ideas innovadoras, parte medular del desarrollo de nuestra empresa.</p>
			</div>
		</div>
		<!--<div class="span6 last">
			<h3 itemprop="name"><a href="https://plus.google.com/109001202683700563599?rel=author" title="Google Plus profile">Saul Martínez</a></h3>
			<div itemprop="description">
				<p> Programador y desarrollador web. Devorador de libros libre de distinciones de temáticas e idiomas. Músico ocasional y generador de ideas innovadoras, parte medular del desarrollo de nuestra empresa.</p>
			</div>
		</div>
	</div>
		<div class="hr">
		&nbsp;
	</div>-->
	<div itemscope itemtype="http://schema.org/Person">
		<div class="span3 team-social">
			<img src="<?= $this->absoluteUrl('/img/team/elalexissanchez.jpg') ?>" alt="Alexis Sanchez" width="205" height="154" itemprop="image">
			<h3 itemprop="name"><a href="https://plus.google.com/109652385173309562635?rel=author" title="Google Plus profile">Alexis Sánchez</a></h3>
			<ul>
				<li>
					<img src="<?= $this->baseUrl('/img/twitter.png') ?>" alt="Alexis Sanchez on Twitter" width="16" height="16">
					<a target="_blank" href="http://twitter.com/elalexissanchez" title="Alexis Sanchez on Twitter">@elalexissanchez</a>
				</li>
				<li>
					<img src="<?= $this->baseUrl('/img/facebook.png') ?>" alt="Saul Martínez on Facebook" width="16" height="16">
					<a target="_blank" href="http://facebook.com/alexissanchezblog" title="Alexis Sanchez on Facebook">Alexis Sanchez</a>
				</li>
			</ul>
			
			<div itemprop="description">
				<p> Comunicólogo y desarrollador de estrategias de marketing electrónico. Autor de libros incompletos, hincha de pumas y adicto a la cafeína. Taquero insaciable y activo de reciente adquisición para el corporativo.</p>
			</div>
		</div><!--
		<div class="span6 last">
			<h3 itemprop="name"><a href="https://plus.google.com/109652385173309562635?rel=author" title="Google Plus profile">Alexis Sánchez</a></h3>
			<div itemprop="description">
				<p> Comunicólogo y desarrollador de estrategias de marketing electrónico. Autor de libros incompletos, hincha de pumas y adicto a la cafeína. Taquero insaciable y activo de reciente adquisición para el corporativo.</p>
			</div>
		</div>
	</div>
		<div class="hr">
		&nbsp;
	</div>-->
	<div itemscope itemtype="http://schema.org/Person">
		<div class="span3 team-social last">
			<img src="<?= $this->absoluteUrl('/img/team/ruben-torres.jpg') ?>" alt="Ruben Torres" width="205" height="154" itemprop="image">
			<h3 itemprop="name"><a href="https://plus.google.com/116728502141184121735?rel=author" title="Google Plus profile">Ruben Torres</a></h3>
			<ul>
				<li>
					<img src="<?= $this->baseUrl('/img/twitter.png') ?>" alt="Ruben Torres on Twitter" width="16" height="16">
					<a target="_blank" href="http://twitter.com/sharktelecomm" title="Ruben Torres on Twitter">@sharktelecomm</a>
				</li>
				<li>
					<img src="<?= $this->baseUrl('/img/facebook.png') ?>" alt="Ruben Torres on Facebook" width="16" height="16">
					<a target="_blank" href="http://facebook.com/ruben.torres.906638" title="Ruben Torres on Facebook">Ruben Torres</a>
				</li>
			</ul>

			<div itemprop="description">
				<p>Viajero incansable, conductor resignado mayormente de manera involuntaria. Es nuestro especialista en ventas, de cuyas ganancias obtiene cuanto gadget sale al mercado. Biker de corazón y adicto al trabajo.</p>
			</div>
		</div><!--
		<div class="span6 last">
			<h3 itemprop="name"><a href="https://plus.google.com/116728502141184121735?rel=author" title="Google Plus profile">Ruben Torres</a></h3>
			<div itemprop="description">
				<p>Viajero incansable, conductor resignado mayormente de manera involuntaria. Es nuestro especialista en ventas, de cuyas ganancias obtiene cuanto gadget sale al mercado. Biker de corazón y adicto al trabajo.</p>
			</div>
		</div>
	</div>
	<div class="hr">
		&nbsp;
	</div>-->
	<div itemscope itemtype="http://schema.org/Person">
		<div class="span3 team-social">
			<img src="<?= $this->absoluteUrl('/img/team/isaac-garcia.jpg') ?>" alt="Isaac Garcia" width="205" height="154" itemprop="image">
			<h3 itemprop="name"><a href="https://plus.google.com/u/0/101961074384076127305?rel=author" title="Google Plus profile">Isaac Garcia</a></h3>
			<ul>
				<li>
					<img src="<?= $this->baseUrl('/img/twitter.png') ?>" alt="Isaac Garcia en Twitter" width="16" height="16">
					<a target="_blank" href="http://twitter.com/isaacgarciav" title="Isaac Garcia en Twitter">@isaacgarciav</a>
				</li>
				<li>
					<img src="<?= $this->baseUrl('/img/facebook.png') ?>" alt="Isaac Garcia en Facebook" width="16" height="16">
					<a target="_blank" href="http://www.facebook.com/isaacyaseret" title="Isaac Garcia en Facebook">Isaac Garcia</a>
				</li>
			</ul>

			<div itemprop="description">
				<p>Nuestro representante y especialista en ventas en la ciudad de Tijuana. Usuario empedernido del celular y adicto a su trabajo en internet y redes sociales.</p>
			</div>
		</div><!--
		<div class="span6 last">
			<h3 itemprop="name"><a href="https://plus.google.com/u/0/101961074384076127305?rel=author" title="Google Plus profile">Isaac Garcia</a></h3>
			<div itemprop="description">
				<p>Nuestro representante y especialista en ventas en la ciudad de Tijuana. Usuario empedernido del celular y adicto a su trabajo en internet y redes sociales.</p>
			</div>
		</div>-->
	</div>
</div>