<?
/**
 * Title
 */
$this->headTitle('Gracias');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Gracias.');
?>
<div class="span12 hidden-phone">
	<div class="jumbo">
		<h1 itemprop="name">Gracias</h1>
		<h2>Por suscribirte a nuestro newsletter</h2>
	</div>
</div>
<div class="span3 sidebar left hidden-phone">
		<!-- <?= $this->twitterBootstrapMenu('mainnav', 'list', 'Acerca') ?> -->
	<p id="brochure">
		<a href="<?= $this->baseUrl('/files/sharkwebintelligence-brochure.pdf') ?>" title="Download our brochure">
			Descarga nuestro triptico
		</a>
	</p>
</div>
<div class="span9 content right">
	<div class="span9 last">
		<div id="content">
			<h3>Tu solicitud fue recibida exitosamente</h3>
			<p></p>
			<p>Gracias por tu interés en <strong><?= $this->title ?></strong>.<br /><br /><a href="<?= $this->baseUrl('/') ?>">&laquo; Regresar</a>
			</p>
		</div>
	</div>
</div>