<?
/**
 * Title
 */
$this->headTitle('Portafolio');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Portafolio de clientes.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Portafolio</h1>
		<h2>Conozca nuestro portafolio de clientes</h2>
	</div>
</div>
<div class="span9 content right" id="services-overview">
	<p>Lorem ipsum dolor sit amet.</p>
</div>