<?
/**
 * Title
 */
$this->headTitle('Precios');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Precios de nuestros servicios.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Precios</h1>
		<h2>Lorem ipsum dolor sit amet.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="price-table">
	<table class="table table-striped table-bordered table-condensed">
		<colgroup style="width: 25%;">
		<colgroup style="width: 25%;">
		<colgroup style="width: 25%;">
		<colgroup style="width: 25%;">
		<thead>
			<tr>
				<th id="feature" scope="colgroup"></th>
				<th id="plan-basic" scope="colgroup">
					<span class="heading">Blue Shark</span>
					<span class="price">$10</span>
					<sup>/ mes</sup>
				</th>
				<th id="plan-normal" scope="colgroup">
					<span class="heading">Tigger Shark</span>
					<span class="price">$20</span>
					<sup>/ mes</sup>
				</th>
				<th id="plan-professional" scope="colgroup">
					<span class="heading">Great White</span>
					<span class="price">$30</span>
					<sup>/ mes</sup>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td headers="feature" class="feature">Capacidad (mb)</td>
				<td headers="plan-basic">150</td>
				<td headers="plan-normal">300</td>
				<td headers="plan-professional">700</td>
			</tr>
			<tr>
				<td headers="feature" class="feature">Cuentas de correo</td>
				<td headers="plan-basic">10</td>
				<td headers="plan-normal">50</td>
				<td headers="plan-professional">100</td>
			</tr>
			<tr>
				<td headers="feature" class="feature">Bases de datos</td>
				<td headers="plan-basic">1</td>
				<td headers="plan-normal">5</td>
				<td headers="plan-professional">10</td>
			</tr>
			<tr>
				<td headers="feature" class="feature">PHP & CGI</td>
				<td headers="plan-basic"><img src="<?= $this->baseUrl('/img/tick.png') ?>" alt="Si" width="16" height="16"></td>
				<td headers="plan-normal"><img src="<?= $this->baseUrl('/img/tick.png') ?>" alt="Si" width="16" height="16"></td>
				<td headers="plan-professional"><img src="<?= $this->baseUrl('/img/tick.png') ?>" alt="Si" width="16" height="16"></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td></td>
				<td headers="plan-basic"><a href="#" class="btn btn-success" title="Contratar">Contratar</a></td>
				<td headers="plan-normal"><a href="#" class="btn btn-success" title="Contratar">Contratar</a></td>
				<td headers="plan-professional"><a href="#" class="btn btn-success" title="Contratar">Contratar</a></td>
			</tr>
		</tfoot>
	</table>
	<div class="span9 last">
		<p>Praesent nec aliquet elit. Nullam convallis placerat metus, sit amet ultrices nulla faucibus sit amet. Quisque dictum lorem sed sem pharetra luctus. Donec sed posuere nisl. Aliquam eu vestibulum mauris.</p>
	</div>
</div>