<?
/**
 * Title
 */
$this->headTitle('¿Quiénes somos?');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Acerca de ((Shark Web Intelligence.');
?>
<? $this->placeholder('microdata')->captureStart() ?>
itemscope itemtype="http://schema.org/AboutPage"
<? $this->placeholder('microdata')->captureEnd() ?>
<div class="span12 hidden-phone">
	<div class="jumbo">
		<h3 itemprop="name">¿Quienes somos?</h3>
		<p>conoce nuestra empresa</p>
	</div>
</div>
<div class="span3 sidebar left hidden-phone">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Acerca') ?>
	<p id="brochure">
		<a href="<?= $this->baseUrl('/files/sharkwebintelligence-brochure.pdf') ?>" title="Download our brochure">
			Descarga nuestro triptico
		</a>
	</p>
</div>
<div class="span9 content right">
	<div class="span9 last">
			
			<p itemprop="description">Fundada en el año 2004, Shark Web Intelligence es una empresa especializada en desarrollar soluciones tecnológicas para web, manejo de redes sociales, marketing en línea y análisis estadístico de tráfico.</p>
			<div class="hr"></div>
			<img src="<?= $this->baseUrl('/img/acerca/quienes-somos.jpg') ?>" class="full-width" alt="Conocenos" style="margin-bottom: 30px;" >
			<div class="hr"></div>
			<p><strong>Creamos, desarrollamos e implementamos</strong> websites, estrategias y contenidos para posicionar su nombre y su marca e influir entre sus potenciales clientes.</p>
			<p><strong>Creemos </strong>en la tecnología como medio para alcanzar objetivos de organizaciones y causas. La comunicación eficaz provee soluciones integrales.
			</p>
			<p><strong>Trabajamos</strong> con pasión y entrega trastocando los límites de la creatividad con el fin de satisfacer las necesidades de nuestros clientes.</p>
			<p><strong>Ofrecemos</strong> servicios de inteligencia web para sus desarrollos.</p>
			<p>Somos... <strong>Shark Web Intelligence.</strong></p>
			<div class="center">
			<div>
				<h3>¿Qué esperas para iniciar ese proyecto que tienes en mente?</h3>
			</div>
			</div>
	</div>
</div>