<?
/**
 * Title
 */
$this->headTitle('Servicios');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Nuestros servicios.');
?>
<div class="span12">
	<div class="jumbo">
		<h1>Servicios</h1>
		<h2>Visión General</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Servicios') ?>
</div>
<div class="span9 content right" id="services-web-hosting">
	<div class="span6">
		<img src="<?= $this->baseUrl('/img/pages/servicios.jpg') ?>" alt="Hospedaje web">
	</div>
	<div class="span3 last">
		<h2>Visión General</h2>
		<p>En Shark Web Intelligence, nuestra filosofía esta centrada en la palabra inovación y hemos desarrollado una estrategia para hacer que nuestros clientes tengan la mejor herramienta de promocion de su negocio.</p>
	</div>
	<div class="span9">
		<p>Nuestra solución es una herramienta capaz de controlarse y dirigirse directamenta al objetivo de mercado de tu empresa, muestra los productos y servicios que vendes a quienes te ya te conocen y son tus clientes,  te conecta con quienes aun no son tus clientes mediente anuncios publicitarios en google y facebook, envia a tus clientes ofertas y comunicados mediante correo electronico y finalmente, cuanta con una herramienta de medicion y analisis estadistico del trafico de tu website para que puedas evaluar el resultado de tus esfuerzos publicitarios.</p>
		
	</div>
		<div class="span3 service">
			<h5 class="sitios-web" itemprop="name"><a href="/servicios/websites" title="Websites">Websites</a></h5>
			<p>La parte medular de nuestra solucion es tu website, ya que en este no existen límites y podemos crear todo lo necesario para mostrar ¿quién eres?, ¿qué haces?, ¿qué vendes?, ¿dónde estas? y ¿cómo contactarte?.
			</p>
		</div>
		<div class="span3 service">
			<h5 class="redes-sociales" itemprop="name"><a href="/servicios/redes-sociales" title="Redes Sociales">Redes Sociales</a></h5>
			<p>Las redes sociales son el elemento que nos sirve para llevar a tus clientes directamente a tu website, creamos conversaciones en torno a tu oferta y llevamos directamente al lugar de tu website donde esta toda la informacion de lo que deseas vender.
			</p>
		</div>
		<div class="span3 service last">
			<h5 class="google" itemprop="name"><a href="/servicios/publicidad-en-google" title="Publicidad en Google">Publicidad en Google</a></h5>
			<p>
				Al utilizar a Google como herramienta de promoción hacemos que tu website aparezca de forma privilegiada en los resultados de las consultas de quienes andan buscando los productos y servicios que ofreces.
			</p>
		</div>
		<div class="span3 service">
			<h5 class="facebook" itemprop="name"><a href="/servicios/publicidad-en-facebook" title="Publicidad en Facebook">Publicidad en Facebook</a></h5>
			<p>
				Mediante la publicidad en esta red social podemos mostrar tu oferta a quienes no saben de ti pero que encajan en el perfil ideal de tu objetivo de mercado.
			</p>
		</div>
		<div class="span3 service">
			<h5 class="email-marketing" itemprop="name"><a href="/servicios/email-marketing" title="Campañas por eMail">Campañas por eMail</a></h5>
			<p>
				Esta es una excelente manera de hacer llegar tus ofertas y promociones a tus clientes mediante un volante electronico que tiene un enlace directo a un landing page dedicado a convertir esa visita en una venta.
			</p>
		</div>
		<div class="span3 service last">
			<h5 class="web-analytics" itemprop="name"><a href="/servicios/web-analytics" title="Analisis de tráfico">Analisis de tráfico</a></h5>
			<p>
				Con esta herramienta podemos medir todo lo que pasa en tu website, redes sociales y campañas de correo elecronico, además establecemos objetivos y les damos seguimiento a bien de verificar si este fue alcanzado o requiere de ajustes para lograrse. 
			</p>
		</div>

	<div class="span9 last">
		<blockquote>
			<p>En Shark, estamos convencidos de que un website no es suficiente para tener exito en la promoción de un negocio en internet;  se necesita una solucion integral que muestre, genere conversaciones, promueva, comunique y pueda medirse.</p>
			<p><strong>David Herrera</strong>, President/CEO Shark Web Intelligence.</p>
		</blockquote>
	</div>
</div>