<div class="span3" itemscope itemtype="http://schema.org/ProfessionalService">
	<div class="box service">
		<h5 class="<?= $this->key ?>" itemprop="name">
			<a href="<?= $this->url($this->route, 'services') ?>" title="<?= $this->title ?>"><?= $this->title ?></a>
		</h5>
		<div  itemprop="description">
			<p><?= $this->description ?></p>
			<ul>
				<? foreach ($this->features as $feature) : ?>
				<li><?= $feature ?></li>
				<? endforeach ?>
			</ul>
		</div>
		<a class="more-link" href="<?= $this->url($this->route, 'services') ?>" title="<?= $this->title ?>">Leer m&aacute;s</a>
		<span style="display:none;" itemprop="url"><?= $this->absoluteUrl($this->url($this->route, 'services')) ?></span>
	</div>
</div>