	<hr style="border-top: 1px solid #ccc;" />
	<div class="vcard">
		<p class="fn"><strong><?= Shark_Config::getConfig()->site->title ?></strong></p>
		<p class="addr">
			<span class="street-address">Alfonso Iberri #242</span>
			<br />
			<span class="locality">Guaymas</span>, <span class="region">Sonora</span>
			<br />
			Código postal: <span class="postal-code">85400</span>
			<br />
			<span class="tel">Tel: <span class="value">(622)-222-8633</span></span>
			<br />
			<span class="country">México</span>
		</p>
	</div>
</div>