<div style="width: 600px; padding: 10px; margin: 10px auto; border-radius: 5px; border: 1px solid #ccc; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; color: #555;">
	<p>
		<a href="http://sharkwebintelligence.com" title="Shark Web Intelligence">
			<img src="http://sharkwebintelligence.com/img/logo.png" alt="Shark Web Intelligence" />
		</a>
		<hr style="border-top: 1px solid #ccc;" />
	</p>