<?php
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category  Site
 * @package   Views
 * @author    Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright 2012 Shark Web Intelligence
 * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version   ${CURRENT_VERSION}
 * @link      http://www.sharkwebintelligence.com
 */
?>
<?= $this->render('email/header.phtml') ?>
	<p><strong><?= $this->contact->name ?></strong> <<a href="mailto:<?= $this->contact->email ?>" title="Responder a <?= $this->contact->name ?>"><?= $this->contact->email ?></a>> se ha puesto en contacto.</p>
	<ul>
		<li>
			<p><strong>Nombre</strong>: <?= $this->contact->name ?></p>
		</li>
		<li>
			<p><strong>Asunto</strong>: <?= $this->contact->subject ?></p>
		</li>
		<li>
			<p><strong>Mensaje</strong>:</p>
			<blockquote style="background: url(http://sharkwebintelligence.com/img/blockquote.png) no-repeat top left; margin: 20px 0; padding-left: 60px; color: #555;">
				<?= $this->contact->message ?>
			</blockquote>
		</li>
	</ul>
<?= $this->render('email/footer.phtml') ?>