<?
$date = new Zend_Date($this->post->created_at, null, 'es_MX');
$year = $date->get(Zend_Date::YEAR);
$month = $date->get(Zend_Date::MONTH);
$day = $date->get(Zend_Date::DAY);
$link = array(
	'year' => $year,
	'month' => $month,
	'day' => $day,
	'alias' => $this->post->alias,
	'category_alias' => $this->post->category->alias,
);
?>
<article class="post" itemscope itemtype="http://schema.org/BlogPosting">
	<header>
		<time class="date updated" date="<?= $this->post->created_at ?>">
			<span class="weekday"><?= $date->toString(Zend_Date::WEEKDAY) ?></span>
			<span class="day"><?= $day ?></span>
			<span class="month"><?= $date->toString(Zend_Date::MONTH_NAME) ?></span>
			<span class="year"><?= $year ?></span>
		</time>
		<hgroup>
			<h3 class="entry-title">
				<a href="<?= $this->url($link, 'blog-post') ?>" itemprop="name">
					<?= $this->post->title ?>
				</a>
			</h3>
			<h2>
				<a href="<?= $this->url(array('category_alias' => $this->post->category->alias), 'blog-category') ?>" title="<?= $this->post->category->title ?>"><?= $this->post->category->title ?></a>
			</h2>
		</hgroup>
	</header>
	<div class="hentry" itemprop="description">
		<?= $this->post->intro ?>
	</div>
	<footer>
		<div itemprop="author" class="hcard" itemscope itemtype="http://schema.org/Person">
		<a href="<?= $this->url(array('username' => $this->post->author->username), 'blog-author') ?>" rel="author" title="<?= $this->post->author->name ?>" itemprop="name" class="author">
			<?= $this->post->author->name ?>
		</a>
		<a href="<?= $this->post->author->gplus_profile ?>?prsrc=3" rel="publisher" style="text-decoration:none;display:inline-block;color:#333;text-align:center; font:13px/16px arial,sans-serif;white-space:nowrap;" item="prop">
			<span style="display:inline-block;font-weight:bold;vertical-align:top;margin-right:5px; margin-top:0px;"><?= $this->post->author->name ?></span>
			<span style="display:inline-block;vertical-align:top;margin-right:13px; margin-top:0px;">on</span>
			<img src="//ssl.gstatic.com/images/icons/gplus-16.png" alt="Google+" style="border:0;width:16px;height:16px;"/>
		</a>
	</footer>
</article>