<?
$date = new Zend_Date($this->post->created_at, null, 'es_MX');
$year = $date->get(Zend_Date::YEAR);
$month = $date->get(Zend_Date::MONTH);
$day = $date->get(Zend_Date::DAY);
$link = array(
	'year' => $year,
	'month' => $month,
	'day' => $day,
	'alias' => $this->post->alias,
	'category_alias' => $this->post->category->alias,
);
?>
<article class="post hentry" itemscope itemtype="http://schema.org/BlogPosting">
	<header>
		<time class="date" datetime="<?= $this->post->created_at ?>">
			<span class="weekday"><?= $date->toString(Zend_Date::WEEKDAY) ?></span>
			<span class="day"><?= $day ?></span>
			<span class="month"><?= $date->toString(Zend_Date::MONTH_NAME) ?></span>
			<span class="year"><?= $year ?></span>
		</time>
		<hgroup>
			<h3 class="entry-title">
				<a href="<?= $this->url($link, 'blog-post') ?>" itemprop="name">
					<?= $this->post->title ?>
				</a>
			</h3>
			<h2>
				<a href="<?= $this->url(array('category_alias' => $this->post->category->alias), 'blog-category') ?>" title="<?= $this->post->category->title ?>"><?= $this->post->category->title ?></a>
			</h2>
		</hgroup>
	</header>
	<div class="entry-content" itemprop="description">
		<?= $this->post->intro ?>
	</div>
	<footer>
		<div itemprop="author" class="hcard" itemscope itemtype="http://schema.org/Person">
			<iframe src="http://facebook.com/plugins/comments.php?href=<?= $this->absoluteUrl($this->url($link, 'blog-post')) ?>&permalink=1" scrolling="no" style="overflow: hidden; border: none; width: 130px; height: 16px;" allowTransparency="true"></iframe>
			<a href="<?= $this->url(array('username' => $this->post->author->username), 'blog-author') ?>" rel="author" title="<?= $this->post->author->name ?>" itemprop="name" class="author">
				<?= $this->post->author->name ?>
			</a>
		</div>
	</footer>
</article>