<?php
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Application
 * @package    Blog
 * @subpackage Views
 * @author     Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright  2012 Shark Web Intelligence
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version    ${CURRENT_VERSION}
 * @link       http://www.sharkwebintelligence.com
 */
$this->partialLoop()->setObjectKey('post');

$this->headTitle('Blog - ' . $this->author->name);
$this->headMeta()->setName('author', $this->author->name);
$this->headMeta()->setName('description', 'Artículos por: ' . $this->author->name);
$this->minifyHeadLink()->appendAlternate($this->absoluteUrl($this->url(array('username' => $this->author->username), 'rss-blog-author')), 'application/xml-rss', implode(' - ', $this->headTitle()->getValue()));
?>
<? if ($this->author) : ?>
<div class="span12">
	<div class="jumbo">
		<div class="author">
			<div class="avatar">
				<?= $this->gravatar($this->author->email, array('imgSize' => 50)) ?>
			</div>
			<h1><?= $this->author->name ?></h1>
			<h2><?= $this->author->username ?></h2>
		</div>
	</div>
</div>
<div class="span3 sidebar right">
	<h3>Autores</h3>
	<ul>
	<? foreach ($this->authors as $author) : ?>
		<li>
			<a href="<?= $this->url(array('username' => $author->username), 'blog-author') ?>" title="<?= $author->name ?>">
				<?= $author->name ?>
			</a>
		</li>
	<? endforeach ?>
	</ul>
	<?= $this->blogMenu($this->categories) ?>
	<?= $this->blogArchive(true) ?>
</div>
<div class="span9 content left" id="blog-list">
	<? if ($this->author->posts->count()) : ?>
	<?= $this->partialLoop('posts/_intro.phtml', $this->author->posts) ?>
	<? endif ?>
</div>
<? else : ?>
<div class="alert alert-error">
	<a href="#" class="close" data-dismiss="alert">x</a>
	<h3 class="alert-heading">
		Error
	</h3>
	<p>No existe un autor con el nombre indicado.</p>
<? endif ?>
