<?
/**
 * Title
 */
$this->headTitle('Blog');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Blog');
$this->partialLoop()->setObjectKey('post');
$this->minifyHeadLink()->appendAlternate($this->absoluteUrl($this->url(array(), 'rss-blog')), 'application/xml-rss', implode(' - ', $this->headTitle()->getValue()));
foreach ($this->authors as $author) {
	$this->minifyHeadLink()->appendAlternate($this->absoluteUrl($this->url(array('username' => $author->username), 'rss-blog-author')), 'application/xml-rss', implode(' - ', $this->headTitle()->getValue()) . ' - ' . $author->name);
}
?>
<div class="span12">
	<div class="jumbo">
		<h1>Blog</h1>
		<h2>por David Herrera Vizcaino.</h2>
	</div>
</div>
<div class="span3 sidebar left">
	<h3>Categorías</h3>
	<?= $this->blogMenu($this->categories) ?>
	<?= $this->blogArchive(true) ?>
</div>
<div class="span9 content right" id="blog-list">
	<?= $this->partialLoop('posts/_intro.phtml', $this->posts) ?>
	<?= $this->paginationControl($this->posts, 'Sliding', 'shared/pagination.phtml') ?>
</div>
