<?
/**
 * Title
 */
$this->headTitle('Blog');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Blog');
$this->partialLoop()->setObjectKey('post');
$this->minifyHeadLink()->appendAlternate($this->absoluteUrl($this->url(array(), 'rss-blog')), 'application/xml-rss', implode(' - ', $this->headTitle()->getValue()));
?>
<div class="span12">
	<div class="jumbo">
		<h1>Blog</h1>
		<h2>Lorem ipsum dolor sit amet.</h2>
	</div>
</div>
<div class="span9 content left" id="blog-list">
	<?= $this->partialLoop('posts/_intro.phtml', $this->posts) ?>
	<?= $this->paginationControl($this->posts, 'Sliding', 'shared/pagination.phtml') ?>
</div>
<div class="span3 sidebar right">
	<?= $this->blogMenu($this->categories) ?>
</div>