<?php
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Appliaction
 * @package    Blog
 * @subpackage Views
 * @author     Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright  2012 Shark Web Intelligence
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version    ${CURRENT_VERSION}
 * @link       http://www.sharkwebintelligence.com
 */
$this->partial()->setObjectKey('post');
?>
<? if ($this->post) : ?>
<?= $this->partial('posts/_post.phtml', $this->post) ?>
<? else : ?>
<? endif ?>
<div class="span3 sidebar right">
	<div class="box">
		<div class="author hcard">
			<div class="avatar">
				<?= $this->gravatar($this->post->author->email, array('imgSize' => 50)) ?>
			</div>
			<div class="bio" itemscope itemtype="http://schema.org/Person">
				<h2>
					<a href="<?= $this->url(array('username' => $this->post->author->username), 'blog-author') ?>" title="<?= $this->post->author->name ?>">
					<?= $this->post->author->name ?>
					</a>
				</h2>
				<p><?= $this->post->author->bio ?></p>
				<div class="links">
					<? if ($this->post->author->gplus_profile) : ?>
					<a href="<?= $this->post->author->gplus_profile ?>?prsrc=3" itemprop="url">
						<img src="<?= $this->baseUrl('/img/gplus-16.png') ?>" alt="Google+" width="16" height="16"/>
					</a>
					<? endif ?>
					<? if ($this->post->author->twitter_profile) : ?>
					<a href="<?= $this->post->author->twitter_profile ?>?rel=author">
						<img src="<?= $this->baseUrl('/img/twitter-bird-white-on-blue.png') ?>" alt="Twitter" width="16" height="16" />
					</a>
					<? endif ?>
					<? if ($this->post->author->facebook_profile) : ?>
					<a href="<?= $this->post->author->facebook_profile ?>?rel=author">
						<img src="<?= $this->baseUrl('/img/facebook_logo.png') ?>" alt="Facebook" width="16" height="16" />
					</a>
					<? endif ?>
				</div>
			</div>
		</div>
	</div>
	<?= $this->blogMenu($this->categories) ?>
</div>