<?php
/**
 * Shark Framework
 *
 * LICENSE
 *
 * Copyright  Shark Web Intelligence
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @category   Appliaction
 * @package    Blog
 * @subpackage Views
 * @author     Saul Martinez <saul@sharkwebintelligence.com>
 * @copyright  2012 Shark Web Intelligence
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @version    ${CURRENT_VERSION}
 * @link       http://www.sharkwebintelligence.com
 */
$this->partial()->setObjectKey('post');
?>
<? if ($this->post) : ?>
<?= $this->partial('posts/_post.phtml', $this->post) ?>
<? else : ?>
<? endif ?>
<div class="span3 sidebar right">
	<div class="box">
		<div class="author">
			<div class="avatar">
				<?= $this->gravatar($this->post->author->email, array('imgSize' => 50)) ?>
			</div>
			<div class="bio">
				<h2>
					<a href="<?= $this->url(array('username' => $this->post->author->username), 'blog-author') ?>" title="<?= $this->post->author->name ?>">
					<?= $this->post->author->name ?>
					</a>
				</h2>
				<p><?= $this->post->author->bio ?>
				<a href="<?= $this->post->author->gplus_profile ?>?prsrc=3" rel="publisher" style="text-decoration:none;display:inline-block;color:#333;text-align:center; font:13px/16px arial,sans-serif;white-space:nowrap;" item="prop">
					<span style="display:inline-block;font-weight:bold;vertical-align:top;margin-right:5px; margin-top:0px;"><?= $this->post->author->name ?></span>
					<span style="display:inline-block;vertical-align:top;margin-right:13px; margin-top:0px;">on</span>
					<img src="//ssl.gstatic.com/images/icons/gplus-16.png" alt="Google+" style="border:0;width:16px;height:16px;"/>
				</a>
			</div>
		</div>
	</div>
	<?= $this->blogMenu($this->categories) ?>
</div>