<?
/**
 * Title
 */
$this->headTitle('Baja Salads');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Baja Salads');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Baja Salads</h1>
			<h2>Baja Salads Deli Express</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Portafolio') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<h3>Baja Salads Deli Express</h3>
				<img src="<?= $this->absoluteUrl('img/clients/pages/baja-salads.jpg') ?>" alt="baja salads" itemprop="image" />
			</div>
			<div class="span6">
				<p>Baja Salads Deli Express, es un restaurante de tipo "Fast Food" ubicado en la ciudad de Guaymas, Sonora.</p>
				<p>El reto era posicionar la marca en el mercado local, por lo que desarrollamos una estrategia de promocion en línea la cual consta de los siguientes elementos.</p>
				<ul class="checklist">
					<li>Sitio Web</li>
					<li>Optimizacion de contenidos</li>
					<li>Creacion de perfiles de redes sociales</li>
					<li>Creacion de campañas publicitarias en facebook</li>
					<li>Monitioreo estadistico de trafico</li>
				</ul>
				<div class="clearfix"></div>
				<p>Lorem ipsum consectetur in aliqua ut veniam mollit velit eu sed amet consequat incididunt nisi eiusmod sed dolor aliqua minim anim non id ut incididunt est.</p>
				<p>Lorem ipsum occaecat dolore non fugiat minim sunt amet nostrud Excepteur veniam dolor velit in qui aliquip qui irure sunt non non et occaecat exercitation enim aute labore cupidatat ad dolor ea dolor incididunt in commodo esse est irure id cillum commodo. </p>
			</div>
			<div class="span3 thumbnail last">
				<img src="<?= $this->absoluteUrl('img/clients/baja-salads-snapshot.png') ?>" alt="All Dental" width="215" height="162" itemprop="image" />
				<div class="caption">
					<p><strong>Baja Salads Deli Express</strong><br /><a href="http://bajasalads.com" target="_blank" title="Baja Salads Deli Express" itemprop="url">http://bajasalads.com</a></p>
				</div>
			</div>
		</div>
	</div>
</div>