<?
/**
 * Title
 */
$this->headTitle('Baja Salads');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Baja Salads');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Baja Salads</h1>
			<h2>Baja Salads Deli Express</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Portafolio') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<img src="<?= $this->absoluteUrl('img/clients/pages/baja-salads.jpg') ?>" alt="baja salads" itemprop="image" />
			</div>
			<div class="span9">
				<p>Baja Salads Deli Express, es un restaurante de tipo "Fast Food" ubicado en la ciudad de Guaymas, Sonora.</p>
				<p>El reto era posicionar la marca en el mercado local, por lo que desarrollamos una estrategia de promocion en línea la cual consta de los siguientes elementos.</p>
				<ul class="checklist">
					<li>Sitio Web</li>
					<li>Optimizacion de contenidos</li>
					<li>Creacion de perfiles de redes sociales</li>
					<li>Creacion de campañas publicitarias en facebook</li>
					<li>Monitioreo estadistico de trafico</li>
				</ul>
			</div>
		</div>
	</div>
</div>
