<?
/**
 * Title
 */
$this->headTitle('Periódico Expreso');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Periódico Expreso - Noticias Hermosillo, Guaymas, Obregón, Nogales, Navojoa.');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Periódico Expreso</h1>
			<h2>Noticias Hermosillo, Guaymas, Obregón, Nogales, Navojoa.</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Portafolio') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<a href="http://www.expreso.com.mx/?iframe=true&width=1000&height=600" title="Periódico Expreso" class="external" rel="prettyPhoto">
					<img src="<?= $this->absoluteUrl('img/clients/pages/periodico-expreso.jpg') ?>" alt="Periódico Expreso" itemprop="image" />
				</a>
			</div>
			<div class="span9">
				<ul class="checklist">
					<li>Manejador de contenidos Joomla!</li>
					<li>Diseño de plantilla</li>
					<li>Desarrollo de módulos, components y plugins</li>
					<li>Posicionamiento en motores de búsqueda</li>
				</ul>
			</div>
		</div>
	</div>
</div>
