<?
/**
 * Title
 */
$this->headTitle('Verano con Coki');
/**
 * Meta data
 */
$this->headMeta()->setName('author', 'Shark Web Intelligence');
$this->headMeta()->setName('description', 'Verano con Coki.');
?>
<div itemscope itemtype="http://schema.org/WebApplication">
	<div class="span12">
		<div class="jumbo">
			<h1 itemprop="name">Verano con Coki</h1>
			<h2>Campamento de verano</h2>
		</div>
	</div>
	<div class="span3 sidebar left">
		<?= $this->twitterBootstrapMenu('mainnav', 'list', 'Portafolio') ?>
	</div>
	<div class="span9 content right" id="client" itemprop="description">
		<div class="row">
			<div class="span9">
				<img src="<?= $this->absoluteUrl('img/clients/pages/verano-con-coki.jpg') ?>" alt="Verano con Coki" itemprop="image" />
			</div>
			<div class="span9">
				<ul class="checklist">
					<li>Manejador de contenidos Joomla!</li>
					<li>Diseño de plantilla</li>
					<li>Desarrollo de módulos, components y plugins</li>
					<li>Posicionamiento en motores de búsqueda</li>
				</ul>
			</div>
		</div>
	</div>
</div>
