<div class="span3">
	<div id="logo">
		<h1>
			<a href="<?= $this->baseUrl('/') ?>">
				<span><?= $this->title ?></span>
			</a>
		</h1>
	</div>
</div>
<div class="span9">
	<div id="get-in-touch" class="pull-right visible-desktop">
		<p>Ponte en contacto: <strong>(622)-222-8633</strong></p>
	</div>
	<nav class="nav pull-right">
		<?= $this->twitterBootstrapMenu() ?>
	</nav>
</div>